config/routes.rb
Rails.application.routes.draw do


  root 'issues#index'
  resources :reservable_spaces
  resources :users
  
  resources :issues

  resources :facilities

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/facility.rb
class Facility < ApplicationRecord
end

app/models/issue.rb
class Issue < ApplicationRecord
    belongs_to:user
end

app/models/reservable_space.rb
class ReservableSpace < ApplicationRecord
  belongs_to :facility
end

app/models/user.rb
class User < ApplicationRecord
    has_many :issues, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: %i[show edit destroy]
  def index
    @facilities = Facility.all
  end

  def show
  end

  def new
    @facility = Facility.new
  end
  def destroy
  end
  
  def create
    @facility = Facility.new(facility_params)
    if @facility.save
      redirect_to @facility, notice:"Facility created successfully!"
    else
      puts @facility.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
  end

  private
  def set_facility
    @facility=Facility.find(params[:id])
  end
  def facility_params
    params.require(:facility).permit(:name,:founded,:address,:category,:status,:operating_hours,:rules,:is_reservable,:capacity,:phone_contact,:image_url)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue , only: %i[show edit update destroy]
  def index
    @issues = Issue.all # an array of ActiveRecord:: Relation, 
                        #each element is an issue object
  end

  def show
  end

  def new
    @issue = Issue.new
  end

  def edit
  end

  def create
    @issue = Issue.new(issue_params)
    if @issue.save
      redirect_to @issue, notice:"Issue created successfully!"
    else
      puts @issue.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @issue.update(issue_params)
      redirect_to @issue, notice: "Issue updated successfully!"
    else
      render:edit
    end
  end
  
  def destroy
    @issue.destroy
    redirect_to issues_path,notice: "Issue deleted successfully!"
  end
  
  private
  
  def set_issue
    @issue= Issue.find(params[:id])
  end
  
  def issue_params
    
    #the parameters that must be provided to create the Issue
    params.require(:issue).permit(:description, :status, :issue_type, :user_id,)
  end

end

app/controllers/reservable_spaces_controller.rb
class ReservableSpacesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit destroy]
  
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice:"User created successfully!"
    else
      puts @user.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end
  
  def destroy
    @user.destroy
    redirect_to users_path,notice: "User deleted successfully"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    #used for strong parameters
    #security feature in Rails that prevents
    #malicious users from injecting unauthorized 
    #data
    params.require(:user).permit(:id,:name,:email,:phone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facility_helper.rb
module FacilityHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/reservable_spaces_helper.rb
module ReservableSpacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/facilities/_form.html.erb
<%= form_with(model:facility, local:true) do |form|%>
<% if facility.errors.any?%>
<div class="alert alert-danger">
    <h4>
        <%= pluralize(issue.errors.count,"error")%> prevented this facility from being created)

    </h4>
    <ul>
        <%=facility.errors.full_messages.each do |msg|%>
        <li>
            <%msg%>
        </li>
        <%end%>
    </ul>
</div>
<%end%>

<div class="mb-3">
    <%=form.label :name, class: "form-label"%>
    <%= form.text_field :name, class: "form-control"%>
</div>

<div class="mb-3">
    <%=form.label :founded, class: "form-label"%>
    <%= form.text_field :founded, class: "form-control"%>
</div>

<div class="mb-3">
    <%=form.label :address, class: "form-label"%>
    <%= form.text_field :address, class: "form-control"%>
</div>
<div class="mb-3">
    <%=form.label :type, class: "form-label"%>
    <%= form.text_field :type, class: "form-control"%>
</div>

<div class="mb-3">
    <%=form.label :status, class: "form-label"%>
    <%= form.select :status, ["open","temporarily closed", "under maintenance","needs repair"], {}, class: "form-control"%>
</div>

<div class="mb-3">
    <%=form.label :operating_hours, class: "form-label"%>
    <%= form.text_field :operating_hours, class: "form-control"%>
</div>

<div class="mb-3">
    <%=form.label :rules, class: "form-label"%>
    <%= form.text_area :rules, class: "form-control"%>
</div>

<div class="mb-3">
    <%=form.label :is_reservable, class: "form-label"%>
    <%= form.select :is_reservable, [true,false],{},class:"form-control"%>
</div>

<div class="mb-3">
    <%=form.label :capacity, class: "form-label"%>
    <%=form.text_field :capacity, class:"form-control"%>
</div>

<div class="mb-3">
    <%=form.label :phone_contact,class:"form-label"%>
    <%=form.telephone_field :phone_contact,class:"form-control"%>
</div>

<div class="mb-3">
    <%=form.label:image_url, class:"form-label"%>
    <%=form.text_field:image_url,class:"form-control"%>
</div>

<div class="actions d-flex justify-content-center mb-5">
    <%=form.submit class:"btn btn-primary"%>
</div>

<%end%>

app/views/facilities/edit.html.erb
<h1>Facility#edit</h1>
<p>Find me in app/views/facility/edit.html.erb</p>

app/views/facilities/index.html.erb
<h1 class="text-center">All Facilites</h1>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Category</th>
        <th>Operating hours</th>
        <th>phone_contact</th>
        <th>Image</th>
        <th>Actions</th>
    </tr>

    <%@facilities.each do |fac| %>
        <tr>
            <td><%=fac.name%></td>
            <td><%=fac.address%></td>
            <td><%=fac.category%></td>
            <td><%=fac.operating_hours%></td>
            <td><%=fac.phone_contact%></td>
            <td><img src=<%=fac.image_url%> alt="" style="width:250px; height:150px;"></td>
            <td>
                <%=link_to "Show", facility_path(fac)%>|
                <%=link_to"Edit",edit_facility_path(fac)%>|
                <%=link_to "Delete",facility_path(fac), method: :delete, data: {confirm: "Are you sure?"}%>
            </td>

        </tr>   
    <%end%>
</table>

app/views/facilities/new.html.erb
<h1 class="text-center">Create new facility</h1>
<div class="">
    <%= render "form", facility:@facility%>
</div>

app/views/facilities/show.html.erb
<h1 class="text-center mt-3">Facility view</h1>
<div>
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Founded</th>
            <th>Address</th>
            <th>Category</th>
            <th>Status</th>
            <th>Hours of Operation</th>
            <th>Rules</th>
            <th>Is Reservable</th>
            <th>Capacity</th>
            <th>Phone </th>
            
        </tr>
        <tr>
            <td><%=@facility.id%></td>
            <td><%=@facility.name%></td>
            <td><%=@facility.founded%></td>
            <td><%=@facility.address%></td>
            <td><%=@facility.category%></td>
            <td><%=@facility.status%></td>
            <td><%=@facility.operating_hours%></td>
            <td><%=@facility.rules%></td>
            <td><%=@facility.is_reservable%></td>
            <td><%=@facility.capacity%></td>
            <td><%=@facility.phone_contact%></td>
            
        </tr>
    </table>
    <div class="d-flex justify-content-center mt-5 mb-5">
        <img class="rounded img-fluid" src="<%=@facility.image_url%>" alt="">
    </div>
</div>

app/views/issues/_form.html.erb
<%= form_with(model:issue, local:true) do |form|%>
    <% if issue.errors.any? %>
    <div class="alert alert-danger">
        <h4>
            <%= pluralize(issue.errors.count,"error")%> prohibited this issue from being saved
        </h4>
        <ul>
            <%= issue.errors.full_messages.each do |msg|%>
            <li>
                <%=msg%>
            </li>
            <%end%>
        </ul>
    </div>
<%end%>

<div class="mb-3">
    <%= form.label :description, class: "form-label"%>
    <%= form.text_area :description, class: "form-control"%>
</div>

<div class="mb-3">
    <%=form.label :status, class: "form-label"%>
    <%=form.select :status, ["open", "in progress","resolved"], {}, class:"form-select"%>
</div>

<div class="mb-3">
    <%=form.label :User, class: "form-label"%>
    <%=form.collection_select :user_id, User.all, :id, :name,
    {prompt: "Select a user"},
    {class: 'form-control'}%>
</div>

<div class="mb-3">
    <%= form.label :issue_type, class: "form-label"%>
    <%= form.text_area :issue_type, class: "form-control"%>
</div>

<div class="mb-3 actions">
    <%= form.submit class:"btn btn-primary"%>
</div>
<%end%>

app/views/issues/edit.html.erb
<h1>Issues#edit</h1>
<p>Find me in app/views/issues/edit.html.erb</p>

app/views/issues/index.html.erb
<h1 class="text-center">All Issues</h1>

<table class="table table-striped table-hover">
  <tr>
    <th>Description</th>
    <th>Status</th>
    <th>Category</th>
    <th>Actions</th>
  </tr>

  <% @issues.each do |issue| %>
    <tr>
      <td><%= issue.description %></td>
      <td><%= issue.status %></td>
      <td><%= issue.issue_type %></td>
      <td>
        <%= link_to "Show", issue_path(issue) %> |
        <%= link_to "Edit", edit_issue_path(issue) %> |
        <%= link_to "Delete", issue_path(issue), method: :delete, data: { confirm: "Are you sure?" } %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to "New Issue", new_issue_path, class:"btn btn-primary" %>

app/views/issues/new.html.erb
<h1 class="text-center">Create new issue</h1>
<%# <div class="text-center 
            justify-content-center 
            align-items-center 
            border
            border-4
            rounded-2
            mt-5
            "> %>
        <div class="">
            <%= render "form", issue: @issue%>
            <%= link_to "Back", issues_path, class: "btn btn-primary"%>
        </div>


<%# </div> %>

app/views/issues/show.html.erb
<h1 class="text-center mt-3">Item view</h1>
<div>
    <table class="table">
        <tr>
                <th>Description</th>
                <th>Status</th>
                <th>Issue Type</th>
                <th>Reported by</th>
                <th>Reported on</th>
        </tr>
        <tr>
                <td><p sytle="max-width:50px"><%=@issue.description%></p></td>
                <td ><p><%=@issue.status%></p></td>
                <td ><p><%=@issue.issue_type%></p></td>
                <td ><p><%=@issue.user.name%></p></td>
                <td ><p><%=@issue.created_at%></p></td>
        </tr>
    </table>
    <div class="d-flex flex-row justify-content-center gap-3">
        <%=link_to "Edit", edit_issue_path(@issue), class:"btn btn-primary"%>
        <%=link_to "Back", issues_path, class:"btn btn-primary"%>
        <%= button_to "Delete", issue_path(@issue), method: :delete, class: "btn btn-primary",
        data: {turbo_confirm: "Are you sure?"}%>
    </div>
  

</div>

<%# <div 
    class="text-center 
            justify-content-center 
            align-items-center 
            border
            border-4
            rounded-2
            mt-5
            "> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "City Services Tracker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css", integrity: "sha384...", crossorigin: "anonymous" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js", integrity: "sha384...", crossorigin: "anonymous" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# navigation %>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <%= link_to "City Services", root_path, class: "navbar-brand"%>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <%= link_to "Issues", issues_path, class:"nav-link"%>
            </li>

            <li class="nav-item">
              <%= link_to "Users", users_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%=link_to "Reservable Spaces", new_reservable_space_path,class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "New Issue", new_issue_path, class:"nav-link" %>
            </li>
            
            <li class="nav-item">
              <%=link_to "Facilites",facilities_path,class:"nav-link"%>
            </li>
            
            <li class="nav-item">
              <%=link_to"New Facility",new_facility_path,class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%=link_to"New Reservable Space",new_reservable_space_path,class:"nav-link"%>
            </li>
         
          </ul>
        </div>
      </div>
    </nav>

    <%# flash messages %>
    <div class="container mt-3">
      <% if notice%>
        <div class="alert alert-success alert-dismissible fade show">
          <%= notice %>
          <button type="button"class="btn-close" data-bs-dismiess="alert"></button>
        </div>
        <% end %>

        <% if alert%>
          <div class="alert alert-danger alert-dismissible fade show">
            <%= alert %>
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
          </div>
        <%end%>
    </div>

    <%# main content %>
    <div class="container mt-4">
      <%= yield%>
    </div>
  </body>
</html>

app/views/reservable_spaces/destroy.html.erb
<h1>ReservableSpaces#destroy</h1>
<p>Find me in app/views/reservable_spaces/destroy.html.erb</p>

app/views/reservable_spaces/edit.html.erb
<h1>ReservableSpaces#edit</h1>
<p>Find me in app/views/reservable_spaces/edit.html.erb</p>

app/views/reservable_spaces/index.html.erb
<h1>ReservableSpaces#index</h1>
<p>Find me in app/views/reservable_spaces/index.html.erb</p>

app/views/reservable_spaces/new.html.erb
<h1>ReservableSpaces#new</h1>
<p>Find me in app/views/reservable_spaces/new.html.erb</p>

app/views/reservable_spaces/show.html.erb
<h1>ReservableSpaces#show</h1>
<p>Find me in app/views/reservable_spaces/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model:user, local:true) do |form|%>
    <% if user.errors.any? %>
    <div class="alert alert-danger">
        <h4>
            <%= pluralize(user.errors.count,"error")%> prohibited this user from being saved
        </h4>
        <ul>
            <%= user.errors.full_messages.each do |msg|%>
            <li>
                <%=msg%>
            </li>
            <%end%>
        </ul>
    </div>
<%end%>
<div class="mb-3">
    <%= form.label :name, class: "form-label"%>
    <%= form.text_field :name, class: "form-control"%>
</div>

<div class="mb-3">
    <%= form.label :email, class: "form-label"%>
    <%= form.email_field :email, class: "form-control"%>
</div>

<div class="mb-3">
    <%=form.label :phone, class: "form-label"%>
    <%=form.telephone_field :phone, class: "form-control"%>
</div>

<div class="actions">
    <%= form.submit class:"btn btn-primary"%>
</div>
<%end%>

app/views/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/users/index.html.erb
<h1 class="text-center">All Users</h1>

<table class="table table-striped table-hover">
  <tr>
    <th>Name</th>
    <th>ID</th>
    <th>email</th>
    <th>phone number</th>
    <th>Actions</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.id %></td>
      <td><%= user.email %></td>
      <td> <%=user.phone %></td>

     <td>
        <%= link_to "Show", user_path(user) %> |
        <%= link_to "Edit", edit_user_path(user) %> |
        <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure?" } %>
      </td>
      
    
      
    </tr>
  <% end %>
</table>

<%= link_to "New User", new_user_path, class:"btn btn-primary"%>

app/views/users/new.html.erb
<h1 class="text-center">Create new user</h1>
<div class="text-center m-3">
    <%= render "form", user: @user%>
    <%= link_to "Back", users_path, class: "btn btn-primary"%>
</div>

app/views/users/show.html.erb
<h1 class="text-center mt-3">User view</h1>
<div 
    class="text-center 
            justify-content-center 
            align-items-center 
            border
            border-4
            rounded-2
            mt-5
            ">

    <table class="table">
        <tr>
                <th>Name</th>
                <th>Id</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Join Date</th>
        </tr>
        <tr>
                <td><p><%=@user.name%></p></td>
                <td><p><%=@user.id%></p></td>
                <td><p><%=@user.email%></p></td>
                <td><p><%=@user.phone%></p></td>
                <td><p><%=@user.created_at%></p></td>
        </tr>
    
    </table>
   
 
     <div class="d-flex gap-3 mt-6 p-4 justify-content-center">
        <%=link_to "Edit", edit_user_path(@user), class:"btn btn-primary"%>
        <%=link_to "Back", users_path, class: "btn btn-primary"%>
        <%= button_to "Delete", user_path(@user), class:"btn btn-primary" ,method: :delete,
                data: {turbo_confirm: "Are you sure?"}%>

     </div>
     
</div>